# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "UI Monitor"
email: stephan@appbieger.com
tagline: UI Monitor
description: >- # this means to ignore newlines until "baseurl:"
  Schützen Sie Ihr Unternehmen indem Sie Ihre Mitarbeiter sicher durch die Pandemie führen. Schaffen Sie Transparenz über die aktuelle Situation an Ihren Unternehmensstandorten. corona fallzahlen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ui-monitor.com" # the base hostname & protocol for your site, e.g. http://example.com
 

author:
  name: Stephan Tomforde
  twitter: stephantomforde
  image: /img/members/StephanTomforde.jpg
twitter:
  username: stephantomforde
  card: summary_large_image
social:
  name: Stephan Tomforde
  links:
    - https://twitter.com/stephantomforde
    - https://www.facebook.com/stomforde
    - https://www.linkedin.com/in/stephan-tomforde-0bb792125
    - https://github.com/appbieger

timezone: Europe/Berlin

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag 
lang: de
github: [metadata]

sass:
  style: compressed
 


exclude: ["video", "imageConverter", "design", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


